// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using gestion_dossier_patient.models;

#nullable disable

namespace gestion_dossier_patient.Migrations
{
    [DbContext(typeof(MedecinContext))]
    [Migration("20240410153031_initDatabase")]
    partial class initDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("gestion_dossier_patient.models.Consultation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date_Consultation")
                        .HasColumnType("datetime2");

                    b.Property<string>("Diagnostique")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Hauteur")
                        .HasColumnType("float");

                    b.Property<double?>("Poids")
                        .HasColumnType("float");

                    b.Property<int?>("medecinId")
                        .HasColumnType("int");

                    b.Property<string>("patientCode")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("medecinId");

                    b.HasIndex("patientCode");

                    b.ToTable("consultation");
                });

            modelBuilder.Entity("gestion_dossier_patient.models.Dossier_patient", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Adresse")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("Date_Enregistrement")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nom")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Prenom")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Sexe")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("Tel")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Code");

                    b.ToTable("dossier_patient");
                });

            modelBuilder.Entity("gestion_dossier_patient.models.Medecins", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Adresse")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Nom")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Prenom")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Sexe")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("Specialite")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Tel")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("medecin");
                });

            modelBuilder.Entity("gestion_dossier_patient.models.Prescription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Prescription_Text")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("consultationId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("consultationId");

                    b.ToTable("prescription");
                });

            modelBuilder.Entity("gestion_dossier_patient.models.Consultation", b =>
                {
                    b.HasOne("gestion_dossier_patient.models.Medecins", "medecin")
                        .WithMany()
                        .HasForeignKey("medecinId");

                    b.HasOne("gestion_dossier_patient.models.Dossier_patient", "patient")
                        .WithMany()
                        .HasForeignKey("patientCode");

                    b.Navigation("medecin");

                    b.Navigation("patient");
                });

            modelBuilder.Entity("gestion_dossier_patient.models.Prescription", b =>
                {
                    b.HasOne("gestion_dossier_patient.models.Consultation", "consultation")
                        .WithMany()
                        .HasForeignKey("consultationId");

                    b.Navigation("consultation");
                });
#pragma warning restore 612, 618
        }
    }
}
